// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DSS_SWP.Models;

public partial class CertificateMainDiamond
{
    public long Id { get; set; }

    public long MainDiamondId { get; set; }

    public string Describe { get; set; }

    public string IsseDate { get; set; }

    public string ExpiryDate { get; set; }

    public string Type { get; set; }

    public int Status { get; set; }
}