// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DSS_SWP.Models;

public partial class DiamondShell
{
    public long Id { get; set; }

    public string Name { get; set; }

    public string Image { get; set; }

    public double? Weight { get; set; }

    public int Status { get; set; }

    public int? MaterialId { get; set; }

    public virtual ICollection<Product> Products { get; set; } = new List<Product>();
}