// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DSS_SWP.Models;

public partial class DiamondPriceList
{
    public long Id { get; set; }

    public double Price { get; set; }

    public string Clarity { get; set; }

    public string Color { get; set; }

    public string Origin { get; set; }

    public string Cut { get; set; }

    public string CaraWeight { get; set; }
}