// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DSS_SWP.Models;

public partial class MainDiamond
{
    public long Id { get; set; }

    public string Shape { get; set; }

    public string Origin { get; set; }

    public string CaraWeight { get; set; }

    public string Clarity { get; set; }

    public string Color { get; set; }

    public string Image { get; set; }

    public string Describe { get; set; }

    public long Quantity { get; set; }

    public string Cut { get; set; }

    public string Polish { get; set; }

    public string Symmetry { get; set; }

    public string Measurements { get; set; }

    public string Culet { get; set; }

    public string Fluorescence { get; set; }

    public int Status { get; set; }

    public virtual ICollection<Product> Products { get; set; } = new List<Product>();
}