// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DSS_SWP.Models;

public partial class Material
{
    public int Id { get; set; }

    public string MaterialName { get; set; }

    public double? Price { get; set; }

    public int? Status { get; set; }
}