// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DSS_SWP.Models;

public partial class OrderDetail
{
    public long Id { get; set; }

    public long OrderId { get; set; }

    public long ProductId { get; set; }

    public double UnitPrice { get; set; }

    public virtual Order Order { get; set; }

    public virtual Product Product { get; set; }
}